// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZsXS3vHqKjLNQ7oPPS5QzPUITsZeX9WI',
    appId: '1:966075316489:android:2c14ca43b4808ab6e1fbd8',
    messagingSenderId: '966075316489',
    projectId: 'road-man-project-auth',
    storageBucket: 'road-man-project-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwNN7J_663nrBXl0kaVeS6xbzxJW-j6J0',
    appId: '1:966075316489:ios:a1fdc2c162836463e1fbd8',
    messagingSenderId: '966075316489',
    projectId: 'road-man-project-auth',
    storageBucket: 'road-man-project-auth.firebasestorage.app',
    androidClientId: '966075316489-18p13tm9e48kolg7p8mf5v2mf39uo9tm.apps.googleusercontent.com',
    iosClientId: '966075316489-5b65alqs5uj75guki52tjattv3v0mop4.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadManProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACTvS9QrYKFYRWT79UBl-UQ4O56joLoWI',
    appId: '1:966075316489:web:fc2a01c95a3ced44e1fbd8',
    messagingSenderId: '966075316489',
    projectId: 'road-man-project-auth',
    authDomain: 'road-man-project-auth.firebaseapp.com',
    storageBucket: 'road-man-project-auth.firebasestorage.app',
    measurementId: 'G-ML9YPMCF5V',
  );

}